version: '2.1'
services:
    jellyfin:
        container_name: jellyfin
        image: lscr.io/linuxserver/jellyfin:latest
        user: 1001:1001
        environment:
            - PUID=1001
            - PGID=1001
            - TZ=Asia/Kolkata
        volumes:
            - ./configs/jellyfin:/config
            - Media:/media
        group_add:
            - '110'
        network_mode: 'host'
        ports:
            - 8096:8096
        devices:
            - /dev/dri/renderD128:/dev/dri/renderD128
        restart: unless-stopped
    jellyseerr:
        image: fallenbagel/jellyseerr:latest
        container_name: jellyseerr
        hostname: jellyseerr
        networks:
            - ArrStack
        user: 1001:1001
        environment:
            - TZ=Asia/Kolkata
        ports:
            - 5055:5055
        volumes:
            - ./configs/ArrStack/jellyseerr:/config
        restart: unless-stopped
        depends_on:
            - sonarr
            - radarr
    jackett:
        image: lscr.io/linuxserver/jackett:latest
        container_name: jackett
        hostname: jackett
        networks:
            - ArrStack
        environment:
            - PUID=1001
            - PGID=1001
            - TZ=Asia/Kolkata
            - AUTO_UPDATE=true
            - RUN_OPTS= #optional
        volumes:
            - ./configs/ArrStack/jackett:/config
        ports:
            - 9117:9117
        restart: unless-stopped
        depends_on:
            - flaresolverr
    flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        container_name: flaresolverr
        hostname: flaresolverr
        networks:
            - ArrStack
        environment:
            - LOG_LEVEL=${LOG_LEVEL:-info}
            - LOG_HTML=${LOG_HTML:-false}
            - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
            - TZ=Asia/Kolkata
        ports:
            - 8191:8191
        restart: unless-stopped
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        hostname: qbittorrent
        networks:
            - ArrStack
        environment:
            - PUID=1001
            - PGID=1001
            - TZ=Asia/Kolkata
            - WEBUI_PORT=8080
            - TORRENTING_PORT=6881
        volumes:
            - ./configs/ArrStack/qbittorrent:/config
            - Downloads:/downloads
        ports:
            - 8222:8222
            - 6883:6883
            - 6883:6883/udp
        restart: unless-stopped
    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        hostname: radarr
        networks:
            - ArrStack
        environment:
            - PUID=1001
            - PGID=1001
            - TZ=Asia/Kolkata
        volumes:
            - ./configs/ArrStack/radarr:/config
            - Media:/media
            - Downloads:/downloads
        ports:
            - 7878:7878
        restart: unless-stopped
        depends_on:
            - jackett
            - qbittorrent
            - jellyfin
    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        hostname: sonarr
        networks:
            - ArrStack
        environment:
            - PUID=1001
            - PGID=1001
            - TZ=Asia/Kolkata
        volumes:
            - ./configs/ArrStack/sonarr:/config
            - Media:/media
            - Downloads:/downloads
        depends_on:
            - jackett
            - qbittorrent
            - jellyfin
        ports:
            - 8989:8989
        restart: unless-stopped
    tunnel:
        container_name: cloudflared-tunnel
        image: cloudflare/cloudflared
        networks:
            - ArrStack
        restart: unless-stopped
        command: tunnel run
        environment:
            - TUNNEL_TOKEN=cf_token
networks:
    ArrStack:
        driver: bridge
volumes:
    Media:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/ubuntu/Media
    Downloads:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/ubuntu/downloads
